package net.fr0stbyter.mahjong;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@Mod(modid = Mahjong.MODID, name = Mahjong.NAME, version = Mahjong.VERSION)
public class Mahjong {
    public static final String MODID = "mahjong";
    public static final String NAME = "Mahjong";
    public static final String VERSION = "0.1.0";

    public static CreativeTabs tabMahjong;
    public static Block blockMjm1;
    public static Item itemMjm1;
    public static Block blockMjm2;
    public static Item itemMjm2;
    public static Block blockMjm3;
    public static Item itemMjm3;
    public static Block blockMjm4;
    public static Item itemMjm4;
    public static Block blockMjm5;
    public static Item itemMjm5;
    public static Block blockMjm6;
    public static Item itemMjm6;
    public static Block blockMjm7;
    public static Item itemMjm7;
    public static Block blockMjm8;
    public static Item itemMjm8;
    public static Block blockMjm9;
    public static Item itemMjm9;
    public static Block blockMjp1;
    public static Item itemMjp1;
    public static Block blockMjp2;
    public static Item itemMjp2;
    public static Block blockMjp3;
    public static Item itemMjp3;
    public static Block blockMjp4;
    public static Item itemMjp4;
    public static Block blockMjp5;
    public static Item itemMjp5;
    public static Block blockMjp6;
    public static Item itemMjp6;
    public static Block blockMjp7;
    public static Item itemMjp7;
    public static Block blockMjp8;
    public static Item itemMjp8;
    public static Block blockMjp9;
    public static Item itemMjp9;
    public static Block blockMjs1;
    public static Item itemMjs1;
    public static Block blockMjs2;
    public static Item itemMjs2;
    public static Block blockMjs3;
    public static Item itemMjs3;
    public static Block blockMjs4;
    public static Item itemMjs4;
    public static Block blockMjs5;
    public static Item itemMjs5;
    public static Block blockMjs6;
    public static Item itemMjs6;
    public static Block blockMjs7;
    public static Item itemMjs7;
    public static Block blockMjs8;
    public static Item itemMjs8;
    public static Block blockMjs9;
    public static Item itemMjs9;
    public static Block blockMjm5r;
    public static Item itemMjm5r;
    public static Block blockMjp5r;
    public static Item itemMjp5r;
    public static Block blockMjs5r;
    public static Item itemMjs5r;
    public static Block blockMjh1;
    public static Item itemMjh1;
    public static Block blockMjh2;
    public static Item itemMjh2;
    public static Block blockMjh3;
    public static Item itemMjh3;
    public static Block blockMjh4;
    public static Item itemMjh4;
    public static Block blockMjh5;
    public static Item itemMjh5;
    public static Block blockMjh6;
    public static Item itemMjh6;
    public static Block blockMjh7;
    public static Item itemMjh7;
    public static Block blockMjh8;
    public static Item itemMjh8;
    public static Block blockMjf1;
    public static Item itemMjf1;
    public static Block blockMjf2;
    public static Item itemMjf2;
    public static Block blockMjf3;
    public static Item itemMjf3;
    public static Block blockMjf4;
    public static Item itemMjf4;
    public static Block blockMjd1;
    public static Item itemMjd1;
    public static Block blockMjd2;
    public static Item itemMjd2;
    public static Block blockMjd3;
    public static Item itemMjd3;
    public static Block blockRiichibou;
    public static Item itemRiichibou;

    private static void registerRender(Item item)
    {
        Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
    }
    private static void registerRender(Block block)
    {
        Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(Item.getItemFromBlock(block), 0, new ModelResourceLocation(block.getRegistryName(), "inventory"));
    }
    @EventHandler
    public void preLoad(FMLPreInitializationEvent event) {
        tabMahjong = new CreativeTabs("mahjong") {
            @Override
            @SideOnly(Side.CLIENT)
            public Item getTabIconItem() {
                return Mahjong.itemMjm1;
            }
        };
        blockMjm1 = new BlockMj(Material.clay).setRegistryName("mjm1").setUnlocalizedName("1man");
        itemMjm1 = new ItemBlock(blockMjm1).setRegistryName("mjm1").setUnlocalizedName("1man");
        blockMjm2 = new BlockMj(Material.clay).setRegistryName("mjm2").setUnlocalizedName("2man");
        itemMjm2 = new ItemBlock(blockMjm2).setRegistryName("mjm2").setUnlocalizedName("2man");
        blockMjm3 = new BlockMj(Material.clay).setRegistryName("mjm3").setUnlocalizedName("3man");
        itemMjm3 = new ItemBlock(blockMjm3).setRegistryName("mjm3").setUnlocalizedName("3man");
        blockMjm4 = new BlockMj(Material.clay).setRegistryName("mjm4").setUnlocalizedName("4man");
        itemMjm4 = new ItemBlock(blockMjm4).setRegistryName("mjm4").setUnlocalizedName("4man");
        blockMjm5 = new BlockMj(Material.clay).setRegistryName("mjm5").setUnlocalizedName("5man");
        itemMjm5 = new ItemBlock(blockMjm5).setRegistryName("mjm5").setUnlocalizedName("5man");
        blockMjm6 = new BlockMj(Material.clay).setRegistryName("mjm6").setUnlocalizedName("6man");
        itemMjm6 = new ItemBlock(blockMjm6).setRegistryName("mjm6").setUnlocalizedName("6man");
        blockMjm7 = new BlockMj(Material.clay).setRegistryName("mjm7").setUnlocalizedName("7man");
        itemMjm7 = new ItemBlock(blockMjm7).setRegistryName("mjm7").setUnlocalizedName("7man");
        blockMjm8 = new BlockMj(Material.clay).setRegistryName("mjm8").setUnlocalizedName("8man");
        itemMjm8 = new ItemBlock(blockMjm8).setRegistryName("mjm8").setUnlocalizedName("8man");
        blockMjm9 = new BlockMj(Material.clay).setRegistryName("mjm9").setUnlocalizedName("9man");
        itemMjm9 = new ItemBlock(blockMjm9).setRegistryName("mjm9").setUnlocalizedName("9man");
        blockMjp1 = new BlockMj(Material.clay).setRegistryName("mjp1").setUnlocalizedName("1pin");
        itemMjp1 = new ItemBlock(blockMjp1).setRegistryName("mjp1").setUnlocalizedName("1pin");
        blockMjp2 = new BlockMj(Material.clay).setRegistryName("mjp2").setUnlocalizedName("2pin");
        itemMjp2 = new ItemBlock(blockMjp2).setRegistryName("mjp2").setUnlocalizedName("2pin");
        blockMjp3 = new BlockMj(Material.clay).setRegistryName("mjp3").setUnlocalizedName("3pin");
        itemMjp3 = new ItemBlock(blockMjp3).setRegistryName("mjp3").setUnlocalizedName("3pin");
        blockMjp4 = new BlockMj(Material.clay).setRegistryName("mjp4").setUnlocalizedName("4pin");
        itemMjp4 = new ItemBlock(blockMjp4).setRegistryName("mjp4").setUnlocalizedName("4pin");
        blockMjp5 = new BlockMj(Material.clay).setRegistryName("mjp5").setUnlocalizedName("5pin");
        itemMjp5 = new ItemBlock(blockMjp5).setRegistryName("mjp5").setUnlocalizedName("5pin");
        blockMjp6 = new BlockMj(Material.clay).setRegistryName("mjp6").setUnlocalizedName("6pin");
        itemMjp6 = new ItemBlock(blockMjp6).setRegistryName("mjp6").setUnlocalizedName("6pin");
        blockMjp7 = new BlockMj(Material.clay).setRegistryName("mjp7").setUnlocalizedName("7pin");
        itemMjp7 = new ItemBlock(blockMjp7).setRegistryName("mjp7").setUnlocalizedName("7pin");
        blockMjp8 = new BlockMj(Material.clay).setRegistryName("mjp8").setUnlocalizedName("8pin");
        itemMjp8 = new ItemBlock(blockMjp8).setRegistryName("mjp8").setUnlocalizedName("8pin");
        blockMjp9 = new BlockMj(Material.clay).setRegistryName("mjp9").setUnlocalizedName("9pin");
        itemMjp9 = new ItemBlock(blockMjp9).setRegistryName("mjp9").setUnlocalizedName("9pin");
        blockMjs1 = new BlockMj(Material.clay).setRegistryName("mjs1").setUnlocalizedName("1sou");
        itemMjs1 = new ItemBlock(blockMjs1).setRegistryName("mjs1").setUnlocalizedName("1sou");
        blockMjs2 = new BlockMj(Material.clay).setRegistryName("mjs2").setUnlocalizedName("2sou");
        itemMjs2 = new ItemBlock(blockMjs2).setRegistryName("mjs2").setUnlocalizedName("2sou");
        blockMjs3 = new BlockMj(Material.clay).setRegistryName("mjs3").setUnlocalizedName("3sou");
        itemMjs3 = new ItemBlock(blockMjs3).setRegistryName("mjs3").setUnlocalizedName("3sou");
        blockMjs4 = new BlockMj(Material.clay).setRegistryName("mjs4").setUnlocalizedName("4sou");
        itemMjs4 = new ItemBlock(blockMjs4).setRegistryName("mjs4").setUnlocalizedName("4sou");
        blockMjs5 = new BlockMj(Material.clay).setRegistryName("mjs5").setUnlocalizedName("5sou");
        itemMjs5 = new ItemBlock(blockMjs5).setRegistryName("mjs5").setUnlocalizedName("5sou");
        blockMjs6 = new BlockMj(Material.clay).setRegistryName("mjs6").setUnlocalizedName("6sou");
        itemMjs6 = new ItemBlock(blockMjs6).setRegistryName("mjs6").setUnlocalizedName("6sou");
        blockMjs7 = new BlockMj(Material.clay).setRegistryName("mjs7").setUnlocalizedName("7sou");
        itemMjs7 = new ItemBlock(blockMjs7).setRegistryName("mjs7").setUnlocalizedName("7sou");
        blockMjs8 = new BlockMj(Material.clay).setRegistryName("mjs8").setUnlocalizedName("8sou");
        itemMjs8 = new ItemBlock(blockMjs8).setRegistryName("mjs8").setUnlocalizedName("8sou");
        blockMjs9 = new BlockMj(Material.clay).setRegistryName("mjs9").setUnlocalizedName("9sou");
        itemMjs9 = new ItemBlock(blockMjs9).setRegistryName("mjs9").setUnlocalizedName("9sou");
        blockMjm5r = new BlockMj(Material.clay).setRegistryName("mjm5r").setUnlocalizedName("5manRed");
        itemMjm5r = new ItemBlock(blockMjm5r).setRegistryName("mjm5r").setUnlocalizedName("5manRed");
        blockMjp5r = new BlockMj(Material.clay).setRegistryName("mjp5r").setUnlocalizedName("5pinRed");
        itemMjp5r = new ItemBlock(blockMjp5r).setRegistryName("mjp5r").setUnlocalizedName("5pinRed");
        blockMjs5r = new BlockMj(Material.clay).setRegistryName("mjs5r").setUnlocalizedName("5souRed");
        itemMjs5r = new ItemBlock(blockMjs5r).setRegistryName("mjs5r").setUnlocalizedName("5souRed");
        blockMjh1 = new BlockMj(Material.clay).setRegistryName("mjh1").setUnlocalizedName("chun");
        itemMjh1 = new ItemBlock(blockMjh1).setRegistryName("mjh1").setUnlocalizedName("chun");
        blockMjh2 = new BlockMj(Material.clay).setRegistryName("mjh2").setUnlocalizedName("xia");
        itemMjh2 = new ItemBlock(blockMjh2).setRegistryName("mjh2").setUnlocalizedName("xia");
        blockMjh3 = new BlockMj(Material.clay).setRegistryName("mjh3").setUnlocalizedName("qiu");
        itemMjh3 = new ItemBlock(blockMjh3).setRegistryName("mjh3").setUnlocalizedName("qiu");
        blockMjh4 = new BlockMj(Material.clay).setRegistryName("mjh4").setUnlocalizedName("dong");
        itemMjh4 = new ItemBlock(blockMjh4).setRegistryName("mjh4").setUnlocalizedName("dong");
        blockMjh5 = new BlockMj(Material.clay).setRegistryName("mjh5").setUnlocalizedName("mei");
        itemMjh5 = new ItemBlock(blockMjh5).setRegistryName("mjh5").setUnlocalizedName("mei");
        blockMjh6 = new BlockMj(Material.clay).setRegistryName("mjh6").setUnlocalizedName("lan");
        itemMjh6 = new ItemBlock(blockMjh6).setRegistryName("mjh6").setUnlocalizedName("lan");
        blockMjh7 = new BlockMj(Material.clay).setRegistryName("mjh7").setUnlocalizedName("zhu");
        itemMjh7 = new ItemBlock(blockMjh7).setRegistryName("mjh7").setUnlocalizedName("zhu");
        blockMjh8 = new BlockMj(Material.clay).setRegistryName("mjh8").setUnlocalizedName("ju");
        itemMjh8 = new ItemBlock(blockMjh8).setRegistryName("mjh8").setUnlocalizedName("ju");
        blockMjf1 = new BlockMj(Material.clay).setRegistryName("mjf1").setUnlocalizedName("east");
        itemMjf1 = new ItemBlock(blockMjf1).setRegistryName("mjf1").setUnlocalizedName("east");
        blockMjf2 = new BlockMj(Material.clay).setRegistryName("mjf2").setUnlocalizedName("south");
        itemMjf2 = new ItemBlock(blockMjf2).setRegistryName("mjf2").setUnlocalizedName("south");
        blockMjf3 = new BlockMj(Material.clay).setRegistryName("mjf3").setUnlocalizedName("west");
        itemMjf3 = new ItemBlock(blockMjf3).setRegistryName("mjf3").setUnlocalizedName("west");
        blockMjf4 = new BlockMj(Material.clay).setRegistryName("mjf4").setUnlocalizedName("north");
        itemMjf4 = new ItemBlock(blockMjf4).setRegistryName("mjf4").setUnlocalizedName("north");
        blockMjd1 = new BlockMj(Material.clay).setRegistryName("mjd1").setUnlocalizedName("bai");
        itemMjd1 = new ItemBlock(blockMjd1).setRegistryName("mjd1").setUnlocalizedName("bai");
        blockMjd2 = new BlockMj(Material.clay).setRegistryName("mjd2").setUnlocalizedName("fa");
        itemMjd2 = new ItemBlock(blockMjd2).setRegistryName("mjd2").setUnlocalizedName("fa");
        blockMjd3 = new BlockMj(Material.clay).setRegistryName("mjd3").setUnlocalizedName("zhong");
        itemMjd3 = new ItemBlock(blockMjd3).setRegistryName("mjd3").setUnlocalizedName("zhong");
        blockRiichibou = new BlockRiichibou(Material.clay).setRegistryName("riichibou").setUnlocalizedName("riichibou");
        itemRiichibou = new ItemBlock(blockRiichibou).setRegistryName("riichibou").setUnlocalizedName("riichibou");

        GameRegistry.register(blockMjm1);
        GameRegistry.register(itemMjm1);
        GameRegistry.register(blockMjm2);
        GameRegistry.register(itemMjm2);
        GameRegistry.register(blockMjm3);
        GameRegistry.register(itemMjm3);
        GameRegistry.register(blockMjm4);
        GameRegistry.register(itemMjm4);
        GameRegistry.register(blockMjm5);
        GameRegistry.register(itemMjm5);
        GameRegistry.register(blockMjm6);
        GameRegistry.register(itemMjm6);
        GameRegistry.register(blockMjm7);
        GameRegistry.register(itemMjm7);
        GameRegistry.register(blockMjm8);
        GameRegistry.register(itemMjm8);
        GameRegistry.register(blockMjm9);
        GameRegistry.register(itemMjm9);
        GameRegistry.register(blockMjp1);
        GameRegistry.register(itemMjp1);
        GameRegistry.register(blockMjp2);
        GameRegistry.register(itemMjp2);
        GameRegistry.register(blockMjp3);
        GameRegistry.register(itemMjp3);
        GameRegistry.register(blockMjp4);
        GameRegistry.register(itemMjp4);
        GameRegistry.register(blockMjp5);
        GameRegistry.register(itemMjp5);
        GameRegistry.register(blockMjp6);
        GameRegistry.register(itemMjp6);
        GameRegistry.register(blockMjp7);
        GameRegistry.register(itemMjp7);
        GameRegistry.register(blockMjp8);
        GameRegistry.register(itemMjp8);
        GameRegistry.register(blockMjp9);
        GameRegistry.register(itemMjp9);
        GameRegistry.register(blockMjs1);
        GameRegistry.register(itemMjs1);
        GameRegistry.register(blockMjs2);
        GameRegistry.register(itemMjs2);
        GameRegistry.register(blockMjs3);
        GameRegistry.register(itemMjs3);
        GameRegistry.register(blockMjs4);
        GameRegistry.register(itemMjs4);
        GameRegistry.register(blockMjs5);
        GameRegistry.register(itemMjs5);
        GameRegistry.register(blockMjs6);
        GameRegistry.register(itemMjs6);
        GameRegistry.register(blockMjs7);
        GameRegistry.register(itemMjs7);
        GameRegistry.register(blockMjs8);
        GameRegistry.register(itemMjs8);
        GameRegistry.register(blockMjs9);
        GameRegistry.register(itemMjs9);
        GameRegistry.register(blockMjm5r);
        GameRegistry.register(itemMjm5r);
        GameRegistry.register(blockMjp5r);
        GameRegistry.register(itemMjp5r);
        GameRegistry.register(blockMjs5r);
        GameRegistry.register(itemMjs5r);
        GameRegistry.register(blockMjh1);
        GameRegistry.register(itemMjh1);
        GameRegistry.register(blockMjh2);
        GameRegistry.register(itemMjh2);
        GameRegistry.register(blockMjh3);
        GameRegistry.register(itemMjh3);
        GameRegistry.register(blockMjh4);
        GameRegistry.register(itemMjh4);
        GameRegistry.register(blockMjh5);
        GameRegistry.register(itemMjh5);
        GameRegistry.register(blockMjh6);
        GameRegistry.register(itemMjh6);
        GameRegistry.register(blockMjh7);
        GameRegistry.register(itemMjh7);
        GameRegistry.register(blockMjh8);
        GameRegistry.register(itemMjh8);
        GameRegistry.register(blockMjf1);
        GameRegistry.register(itemMjf1);
        GameRegistry.register(blockMjf2);
        GameRegistry.register(itemMjf2);
        GameRegistry.register(blockMjf3);
        GameRegistry.register(itemMjf3);
        GameRegistry.register(blockMjf4);
        GameRegistry.register(itemMjf4);
        GameRegistry.register(blockMjd1);
        GameRegistry.register(itemMjd1);
        GameRegistry.register(blockMjd2);
        GameRegistry.register(itemMjd2);
        GameRegistry.register(blockMjd3);
        GameRegistry.register(itemMjd3);
        GameRegistry.register(blockRiichibou);
        GameRegistry.register(itemRiichibou);

    }

    @EventHandler
    public void load(FMLInitializationEvent event) {
        registerRender(blockMjm1);
        registerRender(itemMjm1);
        registerRender(blockMjm2);
        registerRender(itemMjm2);
        registerRender(blockMjm3);
        registerRender(itemMjm3);
        registerRender(blockMjm4);
        registerRender(itemMjm4);
        registerRender(blockMjm5);
        registerRender(itemMjm5);
        registerRender(blockMjm6);
        registerRender(itemMjm6);
        registerRender(blockMjm7);
        registerRender(itemMjm7);
        registerRender(blockMjm8);
        registerRender(itemMjm8);
        registerRender(blockMjm9);
        registerRender(itemMjm9);
        registerRender(blockMjp1);
        registerRender(itemMjp1);
        registerRender(blockMjp2);
        registerRender(itemMjp2);
        registerRender(blockMjp3);
        registerRender(itemMjp3);
        registerRender(blockMjp4);
        registerRender(itemMjp4);
        registerRender(blockMjp5);
        registerRender(itemMjp5);
        registerRender(blockMjp6);
        registerRender(itemMjp6);
        registerRender(blockMjp7);
        registerRender(itemMjp7);
        registerRender(blockMjp8);
        registerRender(itemMjp8);
        registerRender(blockMjp9);
        registerRender(itemMjp9);
        registerRender(blockMjs1);
        registerRender(itemMjs1);
        registerRender(blockMjs2);
        registerRender(itemMjs2);
        registerRender(blockMjs3);
        registerRender(itemMjs3);
        registerRender(blockMjs4);
        registerRender(itemMjs4);
        registerRender(blockMjs5);
        registerRender(itemMjs5);
        registerRender(blockMjs6);
        registerRender(itemMjs6);
        registerRender(blockMjs7);
        registerRender(itemMjs7);
        registerRender(blockMjs8);
        registerRender(itemMjs8);
        registerRender(blockMjs9);
        registerRender(itemMjs9);
        registerRender(blockMjm5r);
        registerRender(itemMjm5r);
        registerRender(blockMjp5r);
        registerRender(itemMjp5r);
        registerRender(blockMjs5r);
        registerRender(itemMjs5r);
        registerRender(blockMjh1);
        registerRender(itemMjh1);
        registerRender(blockMjh2);
        registerRender(itemMjh2);
        registerRender(blockMjh3);
        registerRender(itemMjh3);
        registerRender(blockMjh4);
        registerRender(itemMjh4);
        registerRender(blockMjh5);
        registerRender(itemMjh5);
        registerRender(blockMjh6);
        registerRender(itemMjh6);
        registerRender(blockMjh7);
        registerRender(itemMjh7);
        registerRender(blockMjh8);
        registerRender(itemMjh8);
        registerRender(blockMjf1);
        registerRender(itemMjf1);
        registerRender(blockMjf2);
        registerRender(itemMjf2);
        registerRender(blockMjf3);
        registerRender(itemMjf3);
        registerRender(blockMjf4);
        registerRender(itemMjf4);
        registerRender(blockMjd1);
        registerRender(itemMjd1);
        registerRender(blockMjd2);
        registerRender(itemMjd2);
        registerRender(blockMjd3);
        registerRender(itemMjd3);
        registerRender(blockRiichibou);
        registerRender(itemRiichibou);

    }

    @EventHandler
    public void postLoad(FMLPostInitializationEvent event) {
    }
}
